{
  "formatVersion": "1.1",
  "component": {
    "url": "../../aws-http/1.3.39-preview/aws-http-1.3.39-preview.module",
    "group": "aws.sdk.kotlin",
    "module": "aws-http",
    "version": "1.3.39-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth-aws",
          "version": {
            "requires": "1.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "aws-http-jvm-1.3.39-preview.jar",
          "url": "aws-http-jvm-1.3.39-preview.jar",
          "size": 68963,
          "sha512": "b183a9b0ad15fb310c46bbd0e674b805a5f43ec60e742a1c8e99fdf823596129e4f1dcd8aca7338177c28ba0be24c48960c721ff967c877170a6b59a4b12965a",
          "sha256": "388c36606d8a0a356e082ca2d4f9933eb6c305c7bed79640991a331dcea13796",
          "sha1": "77b6b903dd5e7912885bc4b167abf65caf377a42",
          "md5": "777ca2978385fe2f6bf93857ea9e1ae1"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth-aws",
          "version": {
            "requires": "1.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "aws-http-jvm-1.3.39-preview.jar",
          "url": "aws-http-jvm-1.3.39-preview.jar",
          "size": 68963,
          "sha512": "b183a9b0ad15fb310c46bbd0e674b805a5f43ec60e742a1c8e99fdf823596129e4f1dcd8aca7338177c28ba0be24c48960c721ff967c877170a6b59a4b12965a",
          "sha256": "388c36606d8a0a356e082ca2d4f9933eb6c305c7bed79640991a331dcea13796",
          "sha1": "77b6b903dd5e7912885bc4b167abf65caf377a42",
          "md5": "777ca2978385fe2f6bf93857ea9e1ae1"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aws-http-jvm-1.3.39-preview-sources.jar",
          "url": "aws-http-jvm-1.3.39-preview-sources.jar",
          "size": 15599,
          "sha512": "f6f933eb67d5ef29d8125fe82c4441898514d9e7e044e930695f01a46d22c9bf309452a1b9daa6a68d5e2e5ecf1b4eaf213c2f0672ca532f0ad552bad282c485",
          "sha256": "87e6df9f73668d646e3fbce84ccc78113f9f5fd141c8dfe983e5eed51ed59109",
          "sha1": "583cfb2a65d4ca8c3885cc3bfe3cea1478513923",
          "md5": "bd4d8c4a49907eead96ff06dd6751636"
        }
      ]
    }
  ]
}
