{
  "formatVersion": "1.1",
  "component": {
    "group": "aws.sdk.kotlin",
    "module": "version-catalog",
    "version": "1.3.39-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "versionCatalogElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "version-catalog"
      },
      "files": [
        {
          "name": "version-catalog-1.3.39-preview.toml",
          "url": "version-catalog-1.3.39-preview.toml",
          "size": 4505,
          "sha512": "98e6f658f1b67817a638df459d73bbbac4ccaafa3711dcc3c6db02195a56da23adbc2c7312351d6335961410224d49486f6c5531cedc4490c1cee6a2a0868a7a",
          "sha256": "891b10b9a6e0754db4090aa4e7ca3bac1907ea74b39fe8a447fed5d7bb455648",
          "sha1": "d604bc1647ed5c2ccb49cc72f6e3583a9b0aa6e5",
          "md5": "05d24fc9a3afef6052d80ef9257bc919"
        }
      ]
    }
  ]
}
