{
  "formatVersion": "1.1",
  "component": {
    "url": "../../aws-endpoint/1.3.39-preview/aws-endpoint-1.3.39-preview.module",
    "group": "aws.sdk.kotlin",
    "module": "aws-endpoint",
    "version": "1.3.39-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "aws-endpoint-jvm-1.3.39-preview.jar",
          "url": "aws-endpoint-jvm-1.3.39-preview.jar",
          "size": 11208,
          "sha512": "76b2f9a65cc1cdc1a33c2040a7e684b4fdc11479263f129c71c4e24afda48fc6e24b08c347ac36c20fe847e30731eea6f75f75de003ec00cbe6e1fb50bc17aa0",
          "sha256": "cbfc3c6bf5ded554db4554f6d4cd8c62a5d1b68cfc1104185cf5a180cc8d9579",
          "sha1": "1532743c6e115269458ec13890f92a2be2b173ce",
          "md5": "27930b321f7632bfcbe074d9ccea1d4d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.39-preview"
          }
        }
      ],
      "files": [
        {
          "name": "aws-endpoint-jvm-1.3.39-preview.jar",
          "url": "aws-endpoint-jvm-1.3.39-preview.jar",
          "size": 11208,
          "sha512": "76b2f9a65cc1cdc1a33c2040a7e684b4fdc11479263f129c71c4e24afda48fc6e24b08c347ac36c20fe847e30731eea6f75f75de003ec00cbe6e1fb50bc17aa0",
          "sha256": "cbfc3c6bf5ded554db4554f6d4cd8c62a5d1b68cfc1104185cf5a180cc8d9579",
          "sha1": "1532743c6e115269458ec13890f92a2be2b173ce",
          "md5": "27930b321f7632bfcbe074d9ccea1d4d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aws-endpoint-jvm-1.3.39-preview-sources.jar",
          "url": "aws-endpoint-jvm-1.3.39-preview-sources.jar",
          "size": 3067,
          "sha512": "291f1a8ff35259e5539bc66921a5dcd07b7fef500ecb4df04397a9bbbc67efecce7c903e81b1ff3c4d9a05182408b8a901bbef8de67a6aef15d6a8d4843fddd1",
          "sha256": "82009958b18927665f1d8280ca08d55e6728c536be114b78b90c9691f867c0b4",
          "sha1": "acc4179d247b3360c56098fae7f4448703ee1a79",
          "md5": "4fecd2f1523874e4df7c0a8ac9ccd60b"
        }
      ]
    }
  ]
}
