{
  "formatVersion": "1.1",
  "component": {
    "url": "../../aws-config/1.3.39-preview/aws-config-1.3.39-preview.module",
    "group": "aws.sdk.kotlin",
    "module": "aws-config",
    "version": "1.3.39-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-credentials",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "aws-config-jvm-1.3.39-preview.jar",
          "url": "aws-config-jvm-1.3.39-preview.jar",
          "size": 983060,
          "sha512": "210f0b7442fa380ee63dc213e0d81cd7f8e533f12a86fba9f7b4dae6529dffde1c5b8b4e74bc1b097918c5f027c44f94fe2028dd509aca5ea1a22ddfe6595498",
          "sha256": "0578da74aed8f1d423f022d749f2ec4cdf9568b8512e3267789b6052820b2625",
          "sha1": "abc571e90d668722f70d029607a6818cb42b9a01",
          "md5": "569ddeedfde72f1d5bcc9d32eb3fc662"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-credentials",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-api",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client-engine-default",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-http",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde-json",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-protocol-core",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-default",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth-aws",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "identity-api",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "smithy-client",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-defaults",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde-xml",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde-form-url",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-xml-protocols",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-json-protocols",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "aws-config-jvm-1.3.39-preview.jar",
          "url": "aws-config-jvm-1.3.39-preview.jar",
          "size": 983060,
          "sha512": "210f0b7442fa380ee63dc213e0d81cd7f8e533f12a86fba9f7b4dae6529dffde1c5b8b4e74bc1b097918c5f027c44f94fe2028dd509aca5ea1a22ddfe6595498",
          "sha256": "0578da74aed8f1d423f022d749f2ec4cdf9568b8512e3267789b6052820b2625",
          "sha1": "abc571e90d668722f70d029607a6818cb42b9a01",
          "md5": "569ddeedfde72f1d5bcc9d32eb3fc662"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "aws-config-jvm-1.3.39-preview-sources.jar",
          "url": "aws-config-jvm-1.3.39-preview-sources.jar",
          "size": 232194,
          "sha512": "f1dcfc03965bd79234c940f284d9d77ebd4014d01d39fc61137d777c4b9c732b0c37fa823b1c6687e46c04d978c37d50e21cc084992a0388347005ad27b6d02c",
          "sha256": "3a5b032bf2bf296a0dc63229025193668abb9b4ceea65b65937805391ec38f27",
          "sha1": "50ac71cff44be1056a65c85bf1eab16919511e7e",
          "md5": "31797179765dfbedc42d08a4d715d1ad"
        }
      ]
    }
  ]
}
