{
  "formatVersion": "1.1",
  "component": {
    "url": "../../geoplaces/1.3.39-preview/geoplaces-1.3.39-preview.module",
    "group": "aws.sdk.kotlin",
    "module": "geoplaces",
    "version": "1.3.39-preview",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-config",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "smithy-client",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-api",
          "version": {
            "requires": "1.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "geoplaces-jvm-1.3.39-preview.jar",
          "url": "geoplaces-jvm-1.3.39-preview.jar",
          "size": 977296,
          "sha512": "fa57d80611cb2d09436f064e90ed1ba8fd7996c11bc153afcb7ebd7051819b9888f1c12595323c3ab7d03e724f5815d0ebc5ede5578f4fe00daa6c4e00394e13",
          "sha256": "0900382e43d01223905b9b6a5a1c0f4e2376ef3992ba5b85435ab3d42c657050",
          "sha1": "010a9fbea564cf6aa4cbda3f531e4e30adfa58d4",
          "md5": "6d80606955c1213ff7c076d1cd865298"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.10"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-config",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-core",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-endpoint",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "runtime-core",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "smithy-client",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-api",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-credentials",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.sdk.kotlin",
          "module": "aws-http",
          "version": {
            "requires": "1.3.39-preview"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-json-protocols",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-protocol-core",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-common",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "aws-signing-default",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-auth-aws",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "http-client-engine-default",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "identity-api",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "serde-json",
          "version": {
            "requires": "1.3.12"
          }
        },
        {
          "group": "aws.smithy.kotlin",
          "module": "telemetry-defaults",
          "version": {
            "requires": "1.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "geoplaces-jvm-1.3.39-preview.jar",
          "url": "geoplaces-jvm-1.3.39-preview.jar",
          "size": 977296,
          "sha512": "fa57d80611cb2d09436f064e90ed1ba8fd7996c11bc153afcb7ebd7051819b9888f1c12595323c3ab7d03e724f5815d0ebc5ede5578f4fe00daa6c4e00394e13",
          "sha256": "0900382e43d01223905b9b6a5a1c0f4e2376ef3992ba5b85435ab3d42c657050",
          "sha1": "010a9fbea564cf6aa4cbda3f531e4e30adfa58d4",
          "md5": "6d80606955c1213ff7c076d1cd865298"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "geoplaces-jvm-1.3.39-preview-sources.jar",
          "url": "geoplaces-jvm-1.3.39-preview-sources.jar",
          "size": 178530,
          "sha512": "4394c950bfae32e7dcbf03374604e994695d2e7801193d2ba10719e062f79fca1bf6dd033ab9ada818f55349e52dec7b0d18e0f0eb7b906d106a3aca0ebe7641",
          "sha256": "d6bb1e75c1b1c11070ec6b0af38211ada614b193e4b002179fbfd568119b22bf",
          "sha1": "9da19ccade3b24a205311452c13ce2c1940b8b9c",
          "md5": "ff150b5f025674329fde7d00baa99461"
        }
      ]
    }
  ]
}
